# Generated by Django 5.1.15 on 2026-09-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Formal Pants', 'Formal Pants')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('gsm', models.CharField(blank=True, max_length=20)),
                ('fit', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
